query UserFamilies($email: String!) {
  user {
    id
    ownedFamilies {
      id
      name
    }
    families {
      id
      name
      owner {
        id
      }
      kids {
        id
        name
      }
      invitations {
        id
        name
        email
      }
    }
  }
  allInvitations(filter: {email: $email}) {
    id
    family {
      id
      name
      owner {
        id
        name
      }
    }
  }
}
